### PR TITLE
release 1.0.0

### PR DESCRIPTION
**Pull request by bastelfreak**

### CODE REVIEW

**Comment by ekohl** [comment]
I think we should archive this lint check instead. In Puppet 4 it's invalid syntax so I think a syntax check is sufficient. IMHO you should *always* run a syntax check before a lint check, so it's redundant.

**Comment by bastelfreak** [comment]
@ekohl I would like to do a final release and archive the git repo afterwards (like we did it with other plugins).

**Review by ekohl — COMMENTED** [review]
I'm not sure what a 1.0.0 release brings now. Perhaps the summary/description should actually mention that it's obsolete with Puppet 4. A Puppet compile check should give the same error.

**Comment by bastelfreak** [comment]
I added a release-summary. My main idea was to have the correct gemspec/readme published.

**Review by ekohl — APPROVED** [review]
I did think it would be good to include it in the gemspec description but I'm fine either way.

**Pull request merged**
